// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common_setting_cfg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Saidao.Pb {

  /// <summary>Holder for reflection information generated from common_setting_cfg.proto</summary>
  public static partial class CommonSettingCfgReflection {

    #region Descriptor
    /// <summary>File descriptor for common_setting_cfg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonSettingCfgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhjb21tb25fc2V0dGluZ19jZmcucHJvdG8SDWNvbS5zYWlkYW8ucGIaEGVu",
            "dW1fcHJvdG8ucHJvdG8i8AEKE0NvbW1vblNldHRpbmdDb25maWcSIQoDZXRh",
            "GAEgASgCQg/KPgzovpPlh7rmlYjnjodIAIgBARItCg9zZWN0aW9uXzJfbWV0",
            "ZXIYAiABKAJCD8o+DOiKguaVsOi9rOexs0gBiAEBEi0KD21ldGVyXzJfc2Vj",
            "dGlvbhgDIAEoAkIPyj4M57Gz6L2s6IqC5pWwSAKIAQESIgoBZxgEIAEoAkIS",
            "yj4P6YeN5Yqb5Yqg6YCf5bqmSAOIAQFCBgoEX2V0YUISChBfc2VjdGlvbl8y",
            "X21ldGVyQhIKEF9tZXRlcl8yX3NlY3Rpb25CBAoCX2dQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EnumProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Saidao.Pb.CommonSettingConfig), global::Com.Saidao.Pb.CommonSettingConfig.Parser, new[]{ "Eta", "Section2Meter", "Meter2Section", "G" }, new[]{ "Eta", "Section2Meter", "Meter2Section", "G" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CommonSettingConfig : pb::IMessage<CommonSettingConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CommonSettingConfig> _parser = new pb::MessageParser<CommonSettingConfig>(() => new CommonSettingConfig());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CommonSettingConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Saidao.Pb.CommonSettingCfgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonSettingConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonSettingConfig(CommonSettingConfig other) : this() {
      _hasBits0 = other._hasBits0;
      eta_ = other.eta_;
      section2Meter_ = other.section2Meter_;
      meter2Section_ = other.meter2Section_;
      g_ = other.g_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonSettingConfig Clone() {
      return new CommonSettingConfig(this);
    }

    /// <summary>Field number for the "eta" field.</summary>
    public const int EtaFieldNumber = 1;
    private float eta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Eta {
      get { if ((_hasBits0 & 1) != 0) { return eta_; } else { return 0F; } }
      set {
        _hasBits0 |= 1;
        eta_ = value;
      }
    }
    /// <summary>Gets whether the "eta" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEta {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "eta" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEta() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "section_2_meter" field.</summary>
    public const int Section2MeterFieldNumber = 2;
    private float section2Meter_;
    /// <summary>
    /// 1节 = 0.515m/s
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Section2Meter {
      get { if ((_hasBits0 & 2) != 0) { return section2Meter_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        section2Meter_ = value;
      }
    }
    /// <summary>Gets whether the "section_2_meter" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSection2Meter {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "section_2_meter" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSection2Meter() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "meter_2_section" field.</summary>
    public const int Meter2SectionFieldNumber = 3;
    private float meter2Section_;
    /// <summary>
    /// 1m/s = 1.9417节
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Meter2Section {
      get { if ((_hasBits0 & 4) != 0) { return meter2Section_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        meter2Section_ = value;
      }
    }
    /// <summary>Gets whether the "meter_2_section" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMeter2Section {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "meter_2_section" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMeter2Section() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "g" field.</summary>
    public const int GFieldNumber = 4;
    private float g_;
    /// <summary>
    /// 9.8m/s2
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float G {
      get { if ((_hasBits0 & 8) != 0) { return g_; } else { return 0F; } }
      set {
        _hasBits0 |= 8;
        g_ = value;
      }
    }
    /// <summary>Gets whether the "g" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasG {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "g" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearG() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CommonSettingConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CommonSettingConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Eta, other.Eta)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Section2Meter, other.Section2Meter)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Meter2Section, other.Meter2Section)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(G, other.G)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEta) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Eta);
      if (HasSection2Meter) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Section2Meter);
      if (HasMeter2Section) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Meter2Section);
      if (HasG) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(G);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEta) {
        output.WriteRawTag(13);
        output.WriteFloat(Eta);
      }
      if (HasSection2Meter) {
        output.WriteRawTag(21);
        output.WriteFloat(Section2Meter);
      }
      if (HasMeter2Section) {
        output.WriteRawTag(29);
        output.WriteFloat(Meter2Section);
      }
      if (HasG) {
        output.WriteRawTag(37);
        output.WriteFloat(G);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEta) {
        output.WriteRawTag(13);
        output.WriteFloat(Eta);
      }
      if (HasSection2Meter) {
        output.WriteRawTag(21);
        output.WriteFloat(Section2Meter);
      }
      if (HasMeter2Section) {
        output.WriteRawTag(29);
        output.WriteFloat(Meter2Section);
      }
      if (HasG) {
        output.WriteRawTag(37);
        output.WriteFloat(G);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEta) {
        size += 1 + 4;
      }
      if (HasSection2Meter) {
        size += 1 + 4;
      }
      if (HasMeter2Section) {
        size += 1 + 4;
      }
      if (HasG) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CommonSettingConfig other) {
      if (other == null) {
        return;
      }
      if (other.HasEta) {
        Eta = other.Eta;
      }
      if (other.HasSection2Meter) {
        Section2Meter = other.Section2Meter;
      }
      if (other.HasMeter2Section) {
        Meter2Section = other.Meter2Section;
      }
      if (other.HasG) {
        G = other.G;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Eta = input.ReadFloat();
            break;
          }
          case 21: {
            Section2Meter = input.ReadFloat();
            break;
          }
          case 29: {
            Meter2Section = input.ReadFloat();
            break;
          }
          case 37: {
            G = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            Eta = input.ReadFloat();
            break;
          }
          case 21: {
            Section2Meter = input.ReadFloat();
            break;
          }
          case 29: {
            Meter2Section = input.ReadFloat();
            break;
          }
          case 37: {
            G = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
