// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dynamics_info_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Saidao.Pb {

  /// <summary>Holder for reflection information generated from dynamics_info_proto.proto</summary>
  public static partial class DynamicsInfoProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for dynamics_info_proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DynamicsInfoProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlkeW5hbWljc19pbmZvX3Byb3RvLnByb3RvEg1jb20uc2FpZGFvLnBiGhBl",
            "bnVtX3Byb3RvLnByb3RvItwBChBEeW5hbWljSW5mb1NoZWV0EhYKAmlkGAEg",
            "ASgFQgXKPgJJREgAiAEBEjUKFG1heF9hbmd1bGFyX3ZlbG9jaXR5GAIgASgC",
            "QhLKPg/mnIDlpKfop5LpgJ/luqZIAYgBARI8ChhtYXhfYW5ndWxhcl9hY2Nl",
            "bGVyYXRpb24YAyABKAJCFco+EuacgOWkp+inkuWKoOmAn+W6pkgCiAEBQgUK",
            "A19pZEIXChVfbWF4X2FuZ3VsYXJfdmVsb2NpdHlCGwoZX21heF9hbmd1bGFy",
            "X2FjY2VsZXJhdGlvblAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EnumProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Saidao.Pb.DynamicInfoSheet), global::Com.Saidao.Pb.DynamicInfoSheet.Parser, new[]{ "Id", "MaxAngularVelocity", "MaxAngularAcceleration" }, new[]{ "Id", "MaxAngularVelocity", "MaxAngularAcceleration" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DynamicInfoSheet : pb::IMessage<DynamicInfoSheet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DynamicInfoSheet> _parser = new pb::MessageParser<DynamicInfoSheet>(() => new DynamicInfoSheet());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DynamicInfoSheet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Saidao.Pb.DynamicsInfoProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicInfoSheet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicInfoSheet(DynamicInfoSheet other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      maxAngularVelocity_ = other.maxAngularVelocity_;
      maxAngularAcceleration_ = other.maxAngularAcceleration_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicInfoSheet Clone() {
      return new DynamicInfoSheet(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "max_angular_velocity" field.</summary>
    public const int MaxAngularVelocityFieldNumber = 2;
    private float maxAngularVelocity_;
    /// <summary>
    /// 4°/s
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxAngularVelocity {
      get { if ((_hasBits0 & 2) != 0) { return maxAngularVelocity_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        maxAngularVelocity_ = value;
      }
    }
    /// <summary>Gets whether the "max_angular_velocity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxAngularVelocity {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "max_angular_velocity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxAngularVelocity() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "max_angular_acceleration" field.</summary>
    public const int MaxAngularAccelerationFieldNumber = 3;
    private float maxAngularAcceleration_;
    /// <summary>
    /// 1°/s2
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxAngularAcceleration {
      get { if ((_hasBits0 & 4) != 0) { return maxAngularAcceleration_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        maxAngularAcceleration_ = value;
      }
    }
    /// <summary>Gets whether the "max_angular_acceleration" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxAngularAcceleration {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "max_angular_acceleration" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxAngularAcceleration() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DynamicInfoSheet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DynamicInfoSheet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxAngularVelocity, other.MaxAngularVelocity)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxAngularAcceleration, other.MaxAngularAcceleration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasMaxAngularVelocity) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxAngularVelocity);
      if (HasMaxAngularAcceleration) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxAngularAcceleration);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasMaxAngularVelocity) {
        output.WriteRawTag(21);
        output.WriteFloat(MaxAngularVelocity);
      }
      if (HasMaxAngularAcceleration) {
        output.WriteRawTag(29);
        output.WriteFloat(MaxAngularAcceleration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasMaxAngularVelocity) {
        output.WriteRawTag(21);
        output.WriteFloat(MaxAngularVelocity);
      }
      if (HasMaxAngularAcceleration) {
        output.WriteRawTag(29);
        output.WriteFloat(MaxAngularAcceleration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (HasMaxAngularVelocity) {
        size += 1 + 4;
      }
      if (HasMaxAngularAcceleration) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DynamicInfoSheet other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasMaxAngularVelocity) {
        MaxAngularVelocity = other.MaxAngularVelocity;
      }
      if (other.HasMaxAngularAcceleration) {
        MaxAngularAcceleration = other.MaxAngularAcceleration;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 21: {
            MaxAngularVelocity = input.ReadFloat();
            break;
          }
          case 29: {
            MaxAngularAcceleration = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 21: {
            MaxAngularVelocity = input.ReadFloat();
            break;
          }
          case 29: {
            MaxAngularAcceleration = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
