// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ship_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Saidao.Pb {

  /// <summary>Holder for reflection information generated from ship_proto.proto</summary>
  public static partial class ShipProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for ship_proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShipProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBzaGlwX3Byb3RvLnByb3RvEg1jb20uc2FpZGFvLnBiGhBlbnVtX3Byb3Rv",
            "LnByb3RvIo0FCglTaGlwU2hlZXQSGgoCaWQYASABKAVCCco+BuW6j+WPt0gA",
            "iAEBEhwKBG5hbWUYAiABKAlCCco+BuWQjeensEgBiAEBEigKBHR5cGUYAyAB",
            "KA4yCi5FU2hpcFR5cGVCCco+Buexu+Wei0gCiAEBEiwKC3ByZWZhYl9wYXRo",
            "GAQgASgJQhLKPg/pooTliLbkvZPot6/lvoRIA4gBARInCglpY29uX3BhdGgY",
            "BSABKAlCD8o+DOWbvuagh+i3r+W+hEgEiAEBEjQKC2RlcHRoX2RyYWZ0GAYg",
            "ASgCQhrKPhflkIPmsLTmt7HluqbvvIzljZXkvY0gbUgFiAEBEi8KEW1heF9z",
            "ZWN0aW9uX2NvdW50GAcgASgCQg/KPgzmnIDlpKfoiKrpgJ9IBogBARI7Cg5t",
            "YXhfZGVwdGhfZGl2ZRgIIAEoAkIeyj4b5pyA5aSn5LiL5r2c5rex5bqmLOWN",
            "leS9jSBtSAeIAQESKwoKbWF4X3dlaWdodBgJIAEoAkISyj4P5pyA5aSn5o6S",
            "5rC06YePSAiIAQESKAoKbWFpbl9wb3dlchgKIAEoAkIPyj4M5Li75py65Yqf",
            "546HSAmIAQESLQoKZHluYW1pY19pZBgLIAEoBUIUyj4R5Yqo5Yqb5a2m5L+h",
            "5oGvaWRICogBAUIFCgNfaWRCBwoFX25hbWVCBwoFX3R5cGVCDgoMX3ByZWZh",
            "Yl9wYXRoQgwKCl9pY29uX3BhdGhCDgoMX2RlcHRoX2RyYWZ0QhQKEl9tYXhf",
            "c2VjdGlvbl9jb3VudEIRCg9fbWF4X2RlcHRoX2RpdmVCDQoLX21heF93ZWln",
            "aHRCDQoLX21haW5fcG93ZXJCDQoLX2R5bmFtaWNfaWRQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EnumProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Saidao.Pb.ShipSheet), global::Com.Saidao.Pb.ShipSheet.Parser, new[]{ "Id", "Name", "Type", "PrefabPath", "IconPath", "DepthDraft", "MaxSectionCount", "MaxDepthDive", "MaxWeight", "MainPower", "DynamicId" }, new[]{ "Id", "Name", "Type", "PrefabPath", "IconPath", "DepthDraft", "MaxSectionCount", "MaxDepthDive", "MaxWeight", "MainPower", "DynamicId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ShipSheet : pb::IMessage<ShipSheet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShipSheet> _parser = new pb::MessageParser<ShipSheet>(() => new ShipSheet());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShipSheet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Saidao.Pb.ShipProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShipSheet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShipSheet(ShipSheet other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      name_ = other.name_;
      type_ = other.type_;
      prefabPath_ = other.prefabPath_;
      iconPath_ = other.iconPath_;
      depthDraft_ = other.depthDraft_;
      maxSectionCount_ = other.maxSectionCount_;
      maxDepthDive_ = other.maxDepthDive_;
      maxWeight_ = other.maxWeight_;
      mainPower_ = other.mainPower_;
      dynamicId_ = other.dynamicId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShipSheet Clone() {
      return new ShipSheet(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::EShipType type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EShipType Type {
      get { if ((_hasBits0 & 2) != 0) { return type_; } else { return global::EShipType.ShipNone; } }
      set {
        _hasBits0 |= 2;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "prefab_path" field.</summary>
    public const int PrefabPathFieldNumber = 4;
    private string prefabPath_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PrefabPath {
      get { return prefabPath_ ?? ""; }
      set {
        prefabPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "prefab_path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPrefabPath {
      get { return prefabPath_ != null; }
    }
    /// <summary>Clears the value of the "prefab_path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPrefabPath() {
      prefabPath_ = null;
    }

    /// <summary>Field number for the "icon_path" field.</summary>
    public const int IconPathFieldNumber = 5;
    private string iconPath_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IconPath {
      get { return iconPath_ ?? ""; }
      set {
        iconPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "icon_path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIconPath {
      get { return iconPath_ != null; }
    }
    /// <summary>Clears the value of the "icon_path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIconPath() {
      iconPath_ = null;
    }

    /// <summary>Field number for the "depth_draft" field.</summary>
    public const int DepthDraftFieldNumber = 6;
    private float depthDraft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DepthDraft {
      get { if ((_hasBits0 & 4) != 0) { return depthDraft_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        depthDraft_ = value;
      }
    }
    /// <summary>Gets whether the "depth_draft" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDepthDraft {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "depth_draft" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDepthDraft() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "max_section_count" field.</summary>
    public const int MaxSectionCountFieldNumber = 7;
    private float maxSectionCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxSectionCount {
      get { if ((_hasBits0 & 8) != 0) { return maxSectionCount_; } else { return 0F; } }
      set {
        _hasBits0 |= 8;
        maxSectionCount_ = value;
      }
    }
    /// <summary>Gets whether the "max_section_count" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxSectionCount {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "max_section_count" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxSectionCount() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "max_depth_dive" field.</summary>
    public const int MaxDepthDiveFieldNumber = 8;
    private float maxDepthDive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxDepthDive {
      get { if ((_hasBits0 & 16) != 0) { return maxDepthDive_; } else { return 0F; } }
      set {
        _hasBits0 |= 16;
        maxDepthDive_ = value;
      }
    }
    /// <summary>Gets whether the "max_depth_dive" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxDepthDive {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "max_depth_dive" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxDepthDive() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "max_weight" field.</summary>
    public const int MaxWeightFieldNumber = 9;
    private float maxWeight_;
    /// <summary>
    /// 重量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxWeight {
      get { if ((_hasBits0 & 32) != 0) { return maxWeight_; } else { return 0F; } }
      set {
        _hasBits0 |= 32;
        maxWeight_ = value;
      }
    }
    /// <summary>Gets whether the "max_weight" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxWeight {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "max_weight" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxWeight() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "main_power" field.</summary>
    public const int MainPowerFieldNumber = 10;
    private float mainPower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MainPower {
      get { if ((_hasBits0 & 64) != 0) { return mainPower_; } else { return 0F; } }
      set {
        _hasBits0 |= 64;
        mainPower_ = value;
      }
    }
    /// <summary>Gets whether the "main_power" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMainPower {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "main_power" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMainPower() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "dynamic_id" field.</summary>
    public const int DynamicIdFieldNumber = 11;
    private int dynamicId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DynamicId {
      get { if ((_hasBits0 & 128) != 0) { return dynamicId_; } else { return 0; } }
      set {
        _hasBits0 |= 128;
        dynamicId_ = value;
      }
    }
    /// <summary>Gets whether the "dynamic_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDynamicId {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "dynamic_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDynamicId() {
      _hasBits0 &= ~128;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShipSheet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShipSheet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (PrefabPath != other.PrefabPath) return false;
      if (IconPath != other.IconPath) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DepthDraft, other.DepthDraft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxSectionCount, other.MaxSectionCount)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxDepthDive, other.MaxDepthDive)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxWeight, other.MaxWeight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MainPower, other.MainPower)) return false;
      if (DynamicId != other.DynamicId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasType) hash ^= Type.GetHashCode();
      if (HasPrefabPath) hash ^= PrefabPath.GetHashCode();
      if (HasIconPath) hash ^= IconPath.GetHashCode();
      if (HasDepthDraft) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DepthDraft);
      if (HasMaxSectionCount) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxSectionCount);
      if (HasMaxDepthDive) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxDepthDive);
      if (HasMaxWeight) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxWeight);
      if (HasMainPower) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MainPower);
      if (HasDynamicId) hash ^= DynamicId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (HasPrefabPath) {
        output.WriteRawTag(34);
        output.WriteString(PrefabPath);
      }
      if (HasIconPath) {
        output.WriteRawTag(42);
        output.WriteString(IconPath);
      }
      if (HasDepthDraft) {
        output.WriteRawTag(53);
        output.WriteFloat(DepthDraft);
      }
      if (HasMaxSectionCount) {
        output.WriteRawTag(61);
        output.WriteFloat(MaxSectionCount);
      }
      if (HasMaxDepthDive) {
        output.WriteRawTag(69);
        output.WriteFloat(MaxDepthDive);
      }
      if (HasMaxWeight) {
        output.WriteRawTag(77);
        output.WriteFloat(MaxWeight);
      }
      if (HasMainPower) {
        output.WriteRawTag(85);
        output.WriteFloat(MainPower);
      }
      if (HasDynamicId) {
        output.WriteRawTag(88);
        output.WriteInt32(DynamicId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (HasPrefabPath) {
        output.WriteRawTag(34);
        output.WriteString(PrefabPath);
      }
      if (HasIconPath) {
        output.WriteRawTag(42);
        output.WriteString(IconPath);
      }
      if (HasDepthDraft) {
        output.WriteRawTag(53);
        output.WriteFloat(DepthDraft);
      }
      if (HasMaxSectionCount) {
        output.WriteRawTag(61);
        output.WriteFloat(MaxSectionCount);
      }
      if (HasMaxDepthDive) {
        output.WriteRawTag(69);
        output.WriteFloat(MaxDepthDive);
      }
      if (HasMaxWeight) {
        output.WriteRawTag(77);
        output.WriteFloat(MaxWeight);
      }
      if (HasMainPower) {
        output.WriteRawTag(85);
        output.WriteFloat(MainPower);
      }
      if (HasDynamicId) {
        output.WriteRawTag(88);
        output.WriteInt32(DynamicId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasPrefabPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PrefabPath);
      }
      if (HasIconPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconPath);
      }
      if (HasDepthDraft) {
        size += 1 + 4;
      }
      if (HasMaxSectionCount) {
        size += 1 + 4;
      }
      if (HasMaxDepthDive) {
        size += 1 + 4;
      }
      if (HasMaxWeight) {
        size += 1 + 4;
      }
      if (HasMainPower) {
        size += 1 + 4;
      }
      if (HasDynamicId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DynamicId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShipSheet other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasPrefabPath) {
        PrefabPath = other.PrefabPath;
      }
      if (other.HasIconPath) {
        IconPath = other.IconPath;
      }
      if (other.HasDepthDraft) {
        DepthDraft = other.DepthDraft;
      }
      if (other.HasMaxSectionCount) {
        MaxSectionCount = other.MaxSectionCount;
      }
      if (other.HasMaxDepthDive) {
        MaxDepthDive = other.MaxDepthDive;
      }
      if (other.HasMaxWeight) {
        MaxWeight = other.MaxWeight;
      }
      if (other.HasMainPower) {
        MainPower = other.MainPower;
      }
      if (other.HasDynamicId) {
        DynamicId = other.DynamicId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Type = (global::EShipType) input.ReadEnum();
            break;
          }
          case 34: {
            PrefabPath = input.ReadString();
            break;
          }
          case 42: {
            IconPath = input.ReadString();
            break;
          }
          case 53: {
            DepthDraft = input.ReadFloat();
            break;
          }
          case 61: {
            MaxSectionCount = input.ReadFloat();
            break;
          }
          case 69: {
            MaxDepthDive = input.ReadFloat();
            break;
          }
          case 77: {
            MaxWeight = input.ReadFloat();
            break;
          }
          case 85: {
            MainPower = input.ReadFloat();
            break;
          }
          case 88: {
            DynamicId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Type = (global::EShipType) input.ReadEnum();
            break;
          }
          case 34: {
            PrefabPath = input.ReadString();
            break;
          }
          case 42: {
            IconPath = input.ReadString();
            break;
          }
          case 53: {
            DepthDraft = input.ReadFloat();
            break;
          }
          case 61: {
            MaxSectionCount = input.ReadFloat();
            break;
          }
          case 69: {
            MaxDepthDive = input.ReadFloat();
            break;
          }
          case 77: {
            MaxWeight = input.ReadFloat();
            break;
          }
          case 85: {
            MainPower = input.ReadFloat();
            break;
          }
          case 88: {
            DynamicId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
